# Generated by Django 5.2.17 on 2026-08-06 09:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='状态名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统默认值')),
            ],
            options={
                'verbose_name': '客户状态',
                'verbose_name_plural': '客户状态',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='标签名称')),
                ('color', models.CharField(default='#64748b', max_length=7, verbose_name='颜色')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女'), ('未知', '未知')], default='未知', max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('age_note', models.CharField(blank=True, max_length=100, verbose_name='年龄说明')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='手机号')),
                ('wechat_nickname', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='微信昵称')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='地区')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='职业')),
                ('marital_family_note', models.TextField(blank=True, verbose_name='婚姻和家庭说明')),
                ('source', models.CharField(blank=True, max_length=100, verbose_name='客户来源')),
                ('previous_agent', models.CharField(blank=True, max_length=100, verbose_name='原服务人员')),
                ('first_contact_date', models.DateField(blank=True, null=True, verbose_name='首次接触日期')),
                ('last_contact_date', models.DateField(blank=True, null=True, verbose_name='最后联系日期')),
                ('next_followup_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='下次跟进日期')),
                ('priority', models.CharField(choices=[('低', '低'), ('中', '中'), ('高', '高')], default='中', max_length=10, verbose_name='优先级')),
                ('communication_preference', models.CharField(blank=True, max_length=50, verbose_name='沟通偏好')),
                ('notes', models.TextField(blank=True, verbose_name='一般备注')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_customers', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.customerstatus', verbose_name='客户状态')),
                ('tags', models.ManyToManyField(blank=True, related_name='customers', to='customers.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'ordering': ['name'],
            },
        ),
    ]
