# Generated by Django 5.2.17 on 2026-08-06 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_seed_customer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRelation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('relation_type', models.CharField(choices=[('spouse', '配偶'), ('parent_child', '父母子女'), ('family', '其他家庭成员'), ('referrer', '介绍人'), ('same_household', '同一家庭'), ('custom', '其他自定义关系')], max_length=20, verbose_name='关系类型')),
                ('custom_label', models.CharField(blank=True, max_length=50, verbose_name='自定义关系名称')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('from_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='customers.customer', verbose_name='关系发起方')),
                ('to_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='customers.customer', verbose_name='关系对方')),
            ],
            options={
                'verbose_name': '客户关系',
                'verbose_name_plural': '客户关系',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', True), _negated=True), fields=('from_customer', 'to_customer', 'relation_type'), name='uniq_active_relation', violation_error_message='同方向同类型的关系已存在')],
            },
        ),
    ]
