# Generated by Django 5.2.17 on 2026-08-06 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customerrelation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('task_type', models.CharField(choices=[('call', '打电话'), ('wechat', '发微信'), ('meeting', '约见'), ('prepare_materials', '准备资料'), ('followup', '客户回访'), ('policy_organize', '保单整理'), ('claim_material', '理赔补件'), ('event', '参加活动'), ('deliver_materials', '送资料'), ('confirm_payment', '确认缴费'), ('other', '其他')], default='followup', max_length=32, verbose_name='类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
                ('due_date', models.DateField(db_index=True, verbose_name='截止日期')),
                ('due_time', models.TimeField(blank=True, null=True, verbose_name='截止时间')),
                ('priority', models.CharField(choices=[('低', '低'), ('中', '中'), ('高', '高')], default='中', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('open', '未开始'), ('in_progress', '进行中'), ('done', '已完成'), ('cancelled', '已取消')], default='open', max_length=20, verbose_name='状态')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='customers.customer', verbose_name='关联客户')),
            ],
            options={
                'verbose_name': '待办',
                'verbose_name_plural': '待办',
                'ordering': ['due_date', 'created_at'],
            },
        ),
    ]
