# Generated by Django 5.2.17 on 2026-08-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='来源键'),
        ),
    ]
