# Generated by Django 5.2.17 on 2026-08-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_source_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', '未开始'), ('in_progress', '进行中'), ('done', '已完成'), ('cancelled', '已取消')], db_index=True, default='open', max_length=20, verbose_name='状态'),
        ),
    ]
