# Generated by Django 5.2.17 on 2026-08-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_backup',
            field=models.BooleanField(default=False, verbose_name='执行备份或恢复'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_delete_customers',
            field=models.BooleanField(default=False, verbose_name='删除客户'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_download_originals',
            field=models.BooleanField(default=False, verbose_name='下载原文件'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_export_data',
            field=models.BooleanField(default=False, verbose_name='导出数据'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_customers',
            field=models.BooleanField(default=False, verbose_name='创建和编辑客户'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_enums',
            field=models.BooleanField(default=False, verbose_name='管理标签和枚举'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_users',
            field=models.BooleanField(default=False, verbose_name='管理用户'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_permanent_delete',
            field=models.BooleanField(default=False, verbose_name='永久删除'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_audit_logs',
            field=models.BooleanField(default=False, verbose_name='查看审计日志'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_customers',
            field=models.BooleanField(default=False, verbose_name='查看客户'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_sensitive',
            field=models.BooleanField(default=False, verbose_name='查看敏感资料'),
        ),
    ]
