# Generated by Django 5.2.17 on 2026-08-06 09:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=200, unique=True, verbose_name='设置键')),
                ('value', models.JSONField(default=dict, verbose_name='设置值')),
                ('label', models.CharField(blank=True, default='', max_length=200, verbose_name='显示名')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='最后更新人')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='视图名')),
                ('app_label', models.CharField(max_length=100, verbose_name='应用标识')),
                ('model_name', models.CharField(max_length=100, verbose_name='模型名')),
                ('filters', models.JSONField(blank=True, default=dict, verbose_name='过滤条件')),
                ('sorts', models.JSONField(blank=True, default=list, verbose_name='排序条件')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认视图')),
                ('is_shared', models.BooleanField(default=False, verbose_name='共享')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '保存视图',
                'verbose_name_plural': '保存视图',
                'indexes': [models.Index(fields=['owner', 'app_label', 'model_name'], name='core_savedv_owner_i_2a2094_idx')],
            },
        ),
    ]
