# Generated by Django 5.2.17 on 2026-08-06 10:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customerrelation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=100, verbose_name='相册名')),
                ('category', models.CharField(choices=[('id_docs', '客户证件'), ('policy_docs', '保单资料'), ('claim_docs', '理赔资料'), ('hospital_docs', '医院资料'), ('chat_screenshots', '沟通截图'), ('meeting_photos', '见面照片'), ('event_photos', '活动照片'), ('signature_docs', '签字资料'), ('payment_receipts', '缴费凭证'), ('other', '其他资料')], default='other', max_length=32, verbose_name='类别')),
                ('custom_category', models.CharField(blank=True, max_length=100, verbose_name='自定义类别')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='customers.customer', verbose_name='关联客户')),
            ],
            options={
                'verbose_name': '相册',
                'verbose_name_plural': '相册',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('storage_key', models.CharField(max_length=255, unique=True, verbose_name='存储键')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME 类型')),
                ('size', models.BigIntegerField(verbose_name='文件大小')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256')),
                ('taken_at', models.DateTimeField(blank=True, null=True, verbose_name='拍摄时间')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='标题')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('sensitivity', models.CharField(choices=[('normal', '普通'), ('sensitive', '敏感'), ('highly_sensitive', '高敏感')], default='normal', max_length=20, verbose_name='敏感级别')),
                ('is_important', models.BooleanField(default=False, verbose_name='重要标记')),
                ('check_status', models.CharField(choices=[('unchecked', '未核对'), ('checked', '已核对'), ('needs_supplement', '需要补充')], default='unchecked', max_length=20, verbose_name='核对状态')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='来源')),
                ('thumb_storage_key', models.CharField(blank=True, max_length=255, verbose_name='缩略图存储键')),
                ('thumb_mime', models.CharField(blank=True, max_length=50, verbose_name='缩略图 MIME')),
                ('albums', models.ManyToManyField(blank=True, related_name='documents', to='documents.album', verbose_name='关联相册')),
                ('customers', models.ManyToManyField(blank=True, related_name='documents', to='customers.customer', verbose_name='关联客户')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'ordering': ['-created_at'],
            },
        ),
    ]
