# Generated by Django 5.2.17 on 2026-08-06 11:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customerrelation'),
        ('documents', '0002_album_created_by_document_policies'),
        ('policies', '0002_policy_last_paid_batch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='案件名称')),
                ('claim_type', models.CharField(blank=True, choices=[('medical', '医疗'), ('accident', '意外'), ('critical_illness', '重疾'), ('death', '身故'), ('annuity', '年金'), ('other', '其他')], default='other', max_length=100, verbose_name='理赔类型')),
                ('incident_date', models.DateField(blank=True, null=True, verbose_name='出险日期')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='报案日期')),
                ('status', models.CharField(choices=[('consultation', '客户咨询'), ('waiting_materials', '等待客户资料'), ('collecting_materials', '资料收集中'), ('materials_pending_review', '资料待核对'), ('materials_incomplete', '资料不完整'), ('reported', '已报案'), ('submitted', '已提交'), ('insurer_reviewing', '保险公司审核中'), ('requested_supplement', '要求补充材料'), ('approved', '理赔通过'), ('partial_paid', '部分赔付'), ('rejected', '拒赔'), ('disputing', '客户申诉'), ('closed', '已结案')], default='consultation', max_length=30, verbose_name='状态')),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='预估金额')),
                ('actual_paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='实际赔付金额')),
                ('description', models.TextField(blank=True, verbose_name='案件说明')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='结案时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='customers.customer', verbose_name='客户')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='policies.policy', verbose_name='关联保单')),
            ],
            options={
                'verbose_name': '理赔案件',
                'verbose_name_plural': '理赔案件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimMaterial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=200, verbose_name='材料名称')),
                ('is_required', models.BooleanField(default=True, verbose_name='必需材料')),
                ('status', models.CharField(choices=[('not_submitted', '未提交'), ('submitted', '已提交'), ('pending_review', '待核对'), ('checked', '已核对'), ('needs_supplement', '需要补充'), ('not_applicable', '不适用')], default='not_submitted', max_length=20, verbose_name='状态')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='核对时间')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_materials', to=settings.AUTH_USER_MODEL, verbose_name='核对人')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='claims.claimcase', verbose_name='理赔案件')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_materials', to='documents.document', verbose_name='关联文件')),
            ],
            options={
                'verbose_name': '理赔材料',
                'verbose_name_plural': '理赔材料',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimMaterialTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=100, verbose_name='材料名称')),
                ('claim_type', models.CharField(choices=[('medical', '医疗'), ('accident', '意外'), ('critical_illness', '重疾'), ('death', '身故'), ('annuity', '年金'), ('other', '其他')], default='other', max_length=100, verbose_name='理赔类型')),
                ('is_required', models.BooleanField(default=True, verbose_name='必需材料')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '材料清单模板',
                'verbose_name_plural': '材料清单模板',
                'ordering': ['claim_type', 'sort_order', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', True), _negated=True), fields=('claim_type', 'name'), name='uniq_claim_material_template_type_name_active')],
            },
        ),
    ]
