# Generated by Django 5.2.17 on 2026-08-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_seed_claim_material_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimcase',
            name='status',
            field=models.CharField(choices=[('consultation', '客户咨询'), ('waiting_materials', '等待客户资料'), ('collecting_materials', '资料收集中'), ('materials_pending_review', '资料待核对'), ('materials_incomplete', '资料不完整'), ('reported', '已报案'), ('submitted', '已提交'), ('insurer_reviewing', '保险公司审核中'), ('requested_supplement', '要求补充材料'), ('approved', '理赔通过'), ('partial_paid', '部分赔付'), ('rejected', '拒赔'), ('disputing', '客户申诉'), ('closed', '已结案')], db_index=True, default='consultation', max_length=30, verbose_name='状态'),
        ),
    ]
