# Generated by Django 5.2.17 on 2026-08-06 10:19

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customerrelation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('insurer', models.CharField(max_length=100, verbose_name='保险公司')),
                ('name', models.CharField(max_length=200, verbose_name='保单名称')),
                ('policy_no', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='保单号')),
                ('insurance_type', models.CharField(blank=True, max_length=100, verbose_name='险种')),
                ('main_coverage', models.CharField(blank=True, max_length=200, verbose_name='主险')),
                ('rider_note', models.TextField(blank=True, verbose_name='附加险说明')),
                ('application_date', models.DateField(blank=True, null=True, verbose_name='投保日期')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('payment_term', models.CharField(blank=True, max_length=50, verbose_name='缴费期限')),
                ('coverage_term', models.CharField(blank=True, max_length=50, verbose_name='保障期限')),
                ('payment_frequency', models.CharField(blank=True, choices=[('monthly', '月缴'), ('quarterly', '季缴'), ('semi_annual', '半年缴'), ('annual', '年缴'), ('once', '趸缴')], default='annual', max_length=20, verbose_name='缴费频率')),
                ('premium_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='每期保费')),
                ('status', models.CharField(choices=[('active', '正常有效'), ('paying', '缴费中'), ('paid_up', '已缴清'), ('lapsed', '失效'), ('reinstating', '复效处理中'), ('surrendered', '退保'), ('terminated', '解约'), ('matured', '满期'), ('claim_closed', '理赔结案'), ('status_pending', '状态待核实')], default='active', max_length=30, verbose_name='状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('insured', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_policies', to='customers.customer', verbose_name='被保险人')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('policyholder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_policies', to='customers.customer', verbose_name='投保人')),
            ],
            options={
                'verbose_name': '保单',
                'verbose_name_plural': '保单',
            },
        ),
        migrations.CreateModel(
            name='PolicyStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=30, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=30, verbose_name='新状态')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='policies.policy', verbose_name='保单')),
            ],
            options={
                'verbose_name': '保单状态历史',
                'verbose_name_plural': '保单状态历史',
            },
        ),
    ]
