# Generated by Django 5.2.17 on 2026-08-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='last_paid_batch',
            field=models.DateField(blank=True, null=True, verbose_name='最后已缴批次'),
        ),
    ]
