# Generated by Django 5.2.17 on 2026-08-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_policy_last_paid_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='status',
            field=models.CharField(choices=[('active', '正常有效'), ('paying', '缴费中'), ('paid_up', '已缴清'), ('lapsed', '失效'), ('reinstating', '复效处理中'), ('surrendered', '退保'), ('terminated', '解约'), ('matured', '满期'), ('claim_closed', '理赔结案'), ('status_pending', '状态待核实')], db_index=True, default='active', max_length=30, verbose_name='状态'),
        ),
    ]
