# Generated by Django 5.2.17 on 2026-08-06 13:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=50, verbose_name='动作')),
                ('object_type', models.CharField(blank=True, max_length=100, verbose_name='对象类型（模型 label）')),
                ('object_pk', models.CharField(blank=True, max_length=64, verbose_name='对象 ID')),
                ('target_label', models.CharField(blank=True, max_length=200, verbose_name='对象名称（人类可读）')),
                ('result', models.CharField(choices=[('success', '成功'), ('failure', '失败'), ('partial', '部分成功')], default='success', max_length=20, verbose_name='结果')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='上下文')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 地址')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User-Agent')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['object_type', 'object_pk'], name='audit_audit_object__e3cec1_idx')],
            },
        ),
    ]
