# Generated by Django 5.2.17 on 2026-08-06 10:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customerrelation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('channel', models.CharField(choices=[('phone', '电话'), ('wechat', '微信'), ('meeting', '见面'), ('company_activity', '公司活动'), ('home_visit', '上门服务'), ('customer_visit', '客户来访'), ('video_call', '视频通话'), ('sms', '短信'), ('other', '其他')], max_length=32, verbose_name='沟通方式')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='发生时间')),
                ('quick_result', models.CharField(blank=True, choices=[('missed', '未接'), ('hung_up', '挂断'), ('power_off', '关机'), ('empty_number', '空号'), ('declined', '接听但拒绝'), ('wants_wechat', '愿意微信联系'), ('wants_meeting', '愿意见面'), ('time_uncertain', '时间不确定'), ('call_later', '要求稍后联系'), ('not_needed', '明确不需要')], default='', max_length=32, verbose_name='快捷结果')),
                ('content', models.TextField(blank=True, verbose_name='主要内容')),
                ('customer_feedback', models.TextField(blank=True, verbose_name='客户反馈')),
                ('next_plan', models.TextField(blank=True, verbose_name='下一步计划')),
                ('next_followup_date', models.DateField(blank=True, null=True, verbose_name='下次跟进日期')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='customers.customer', verbose_name='客户')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_communications', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
            ],
            options={
                'verbose_name': '沟通记录',
                'verbose_name_plural': '沟通记录',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='已删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('event_type', models.CharField(choices=[('first_meeting', '第一次见面'), ('phone_call', '电话沟通'), ('wechat', '微信沟通'), ('policy_organize', '保单整理'), ('material_collection', '资料收集'), ('claim_process', '理赔处理'), ('customer_activity', '客户活动'), ('home_visit', '上门服务'), ('other', '其他工作过程')], max_length=32, verbose_name='事件类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='发生时间')),
                ('summary', models.TextField(blank=True, verbose_name='结论/主要内容')),
                ('outcome', models.TextField(blank=True, verbose_name='结果')),
                ('next_step', models.TextField(blank=True, verbose_name='下一步')),
                ('next_followup_date', models.DateField(blank=True, null=True, verbose_name='下次跟进日期')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_events', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_events', to='customers.customer', verbose_name='客户')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_work_events', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '工作事件',
                'verbose_name_plural': '工作事件',
                'ordering': ['-occurred_at'],
            },
        ),
    ]
